.TH FARFETCH 1 VERSION
.SH NAME
farfetch - system info
.br
.B farfetch
[-rs] [-l distro]
.SH DESCRIPTION
.PP
System Information
.TP
\fB\,-r\fR
Delete from cache and run (except Haiku)
.TP
\fB\,-s\fR
Small logo display
.TP
\fB\,-l\fR [\fI\,distro\fR]
Displaying different distribution logos (Linux and Illumos only)
.SH AUTHORS
.PP
TechnicalSuwako (Developer)
.br
Hatuhatu Taro (Developer)
